name: Add new packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '37 2 * * *'

jobs:
  add-packages:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("gh", "purrr", "dplyr", "jsonlite"))'

      - name: Add new R packages to packages.json
        run: |
          gh::gh("/orgs/{org}/repos", org = Sys.getenv("GITHUB_REPOSITORY_OWNER"), type = "public") |> 
            purrr::map_chr("full_name") |> 
            purrr::set_names() |> 
            purrr::map(
              ~ gh::gh("/repos/{full_name}/contents/", full_name = .x)
            ) |> 
            purrr::keep(
              ~ "DESCRIPTION" %in% purrr::map(.x, "path")
            ) |> 
            names() |> 
            data.frame(full_name = _) |> 
            dplyr::transmute(
              package = basename(full_name),
              url = file.path("https://github.com", full_name)
            ) |> 
            jsonlite::write_json("packages.json", pretty = TRUE)
        shell: Rscript {0}
        
      - name: Submit packages.json changes in a PR
        uses: peter-evans/create-pull-request@10db75894f6d53fc01c3bb0995e95bd03e583a62
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated update of packages.json
          committer: actions-user <action@github.com>
          author: actions-user <action@github.com>
          branch: new-pkgs
          branch-suffix: timestamp
          add-paths: packages.json
          title: Automated update of packages.json
          delete-branch: true

