name: Check packages' lifecycle

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check-lifecycle:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::jsonlite
            any::purrr
            any::gh
            any::stringr

      - name: Check packages lifecycle
        run: |
          releases <- jsonlite::read_json(
            "packages.json"
          ) |> 
            purrr::map_chr("url") |> 
            stringr::str_remove("^https://github\\.com/") |> 
            purrr::set_names() |> 
            purrr::map(~ gh::gh("/repos/{repo}/releases", repo = .x)) |> 
            lengths()
          
          if (any(releases == 0)) {
            stop(
              "The following packages don't have any release and ",
              "should not be added to the r-universe until they reach a stable state:\n",
              toString(names(releases)[releases == 0])
            )
          }
        shell: Rscript {0}

